language: node_js
addons:
  ssh_known_hosts:
  - nuxt.yawik.org
node_js:
- '10.15.3'
cache:
  directories:
  - node_modules
  - "$HOME/.composer/cache"
  - "$HOME/.npm"
matrix:
  fast_finish: true
  include:
  - php: '7.2'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_c76d5da11a03_key -iv $encrypted_c76d5da11a03_iv
  -in .travis/deploy_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
- curl -LO https://deployer.org/deployer.phar
- chmod +x deployer.phar
install:
- npm install
- npm run generate
script:
- echo "Skipping tests"
deploy:
- provider: script
  skip_cleanup: true
  script: "./deployer.phar deploy"
  on:
    branch: master
